### ISSUE TITLE
USB-based antennas?

### ISSUE THREAD

**Issue by Ocramius** [mretallack/catfeeder#3]
Hey there,

I jumped here after looking at the general topic surrounding the SurePetCare products and their unfortunate decision to use MiWi instead of Zigbee.

This is therefore just a question: I see that you used:

 * a Raspberry PI
 * https://www.mikroe.com/pi-3-click-shield
 * https://www.mikroe.com/bee-click

Based on a quick code skim, I can assume you use the bee-click as a raw antenna, and then used the bundled [MicroChip libraries](https://github.com/mretallack/catfeeder/tree/f7596c5659dc9f87dc3d0edd9e9d8400f9173475/MicroChip) to send raw signals through it?

Is that correct? Do you think (or know) if such an approach would also work through an USB antenna?

My question spawns from the fact that I (attempt to) run all IoT software within docker within a small rack server, kept under strict control. In an ideal world, I'd plug in an USB antenna to the server, then mount the device/make it available as a TTY within the running container (potentially your software).

Do you happen to know if that's remotely possible, or if we're operating at a too high abstraction layer?

As a backref, I'm coming from https://github.com/plambrechtsen/pethublocal/issues/4

EDIT: was thinking of https://www.mikroe.com/click-usb-adapter, basically - if the USB component can just be exposed as a TTY or similar, I can mount it as a docker volume, and then run the software from there. No idea if that makes any sense, or if it is workable at all :D

**Comment by mretallack** [comment]
Hi @Ocramius, using the Click-Usb-Adaptor instead of the Pi should work, you would need to change the interface layer (interface.c) to use the USB interface instead of the Pi's SPI. 

The Click-USB-Adaptor uses a FT2232H, A quick google shows there are two methods of doing this; linux driver and libftdi:

https://christian.amsuess.com/idea-incubator/ftdi-kernel-support/

**Comment by Ocramius** [comment]
Hey @mretallack!

Thank you so much for pointing me in the right direction! I will indeed try this out, thanks, and keep up the good work :muscle:
